### ISSUE TITLE
Listen 1.x deprecation

### ISSUE THREAD

**Issue by nathany** [MicahChalmer/mr-sparkle#3]
Fyi:

The blocking parameter of Listen::Listener#start is deprecated.
Please use Listen::Adapter#start for a non-blocking listener and Listen::Listener#start! for a blocking one.

**Comment by MicahChalmer** [comment]
API dependencies march on, whether you're watching or not...

Released mr-sparkle 0.1.0 which is compatible with (and requires) listen 1.x.

**Comment by nathany** [comment]
Thanks!
