### ISSUE TITLE
Run a specific .rb file?

### ISSUE THREAD

**Issue by ghost** [MicahChalmer/mr-sparkle#8]
Hi,

On Sinatra I was told that mr-sparkle will help me reload code "live" without having to restart.

But I have a directory with several files. Is it possible to tell mr-sparkle specifically which file to run?

If not I would like to suggest adding that as a feature, like

mr-sparkel --run=foo.rb

or some other syntax

**Comment by MicahChalmer** [comment]
This is already possible--just pass it as an argument with no options.  `mr-sparkle foo.rb` or `mr-sparkle -- foo.rb` will run with the rackup file as specified in `foo.rb` instead of the default `config.ru`.
